# Project information
site_name: Another House of Love
site_description: Nothing could enter it but the sincere act
site_author: Andy Tudhope

# Specific to set up
site_url: https://andytudhope.africa/
site_dir: public

# Repository
repo_name: andytudhope/africa
repo_url: https://github.com/andytudhope/africa
edit_uri: ""

extra_css: [extra.css]

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
    #- instant
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  favicon: assets/favicon.png

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/andytudhope
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cryptowanderer

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: andytudhope
      repo: africa
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.extra
  

# Page tree
nav:
  - Home: 'index.md'
  - Essays: 
    - 'Overview': 'essays/index.md'
    - 'Living': 'essays/living-essay.md'
    - 'A Beautiful Question': 'essays/a-beautiful-question.md'
    - 'Martyr of Hope': 'essays/bantu-steve-biko.md'
    - 'Animal’s People': 'essays/animals-people.md' 
    - 'Viewing Time': 'essays/viewing-time.md'
    - 'Blue Devotion': 'essays/blue-devotion.md'
    - 'Language In The Ether': 'essays/language-in-the-ether.md'
    - 'All The Colourful People': 'essays/colourful-people.md'
    - 'Reading As Layered Ritual': 'essays/reading-as-layered-ritual.md'
    - 'Transformative Tools': https://kernel.community/module-3/remember/
    - 'Running Code': https://kernel.community/module-4/consensus/
  - Poetry:
    - 'Overview': 'poetry/index.md'
    - 'Maryam': 'poetry/maryam.md'
    - 'Steel Jasmine': 'poetry/steel-jasmine.md'
    - 'Spring Free': 'poetry/spring-free.md'
    - 'Falcon Heavy': 'poetry/falcon-heavy.md'
    - 'Still Life': 'poetry/still-life.md'
    - 'Basirah': 'poetry/basirah.md'
    - 'The Covenant': 'poetry/covenant.md'
  - Prose:
    - 'Overview': 'prose/index.md'
    - 'Celebrate': 'prose/celebrate.md'
    - 'Rivers of You': 'prose/rivers-of-you.md'
    - 'Father Time': 'prose/father-time.md'
    - 'There’s You In Everything I Do': 'prose/you-in-everything-i-do.md'
  - Academic Work:
    - 'Overview': 'academy/index.md'
    - 'Playing With Time': 'academy/playing-with-time.md'
    - 'Communal Language': 'academy/communal-language.md'
    - 'Yours Sincerely': 'academy/yours-sincerely.md'
  - Soul:
    - 'Pearls': 'soul/index.md'
    - 'Beams': 'soul/beams.md'
    - 'Bursts': 'soul/bursts.md'
    - 'Qur’an': 'soul/quran.md'
